name: Waka Readme

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: zh_CN
          SHOW_LINES_OF_CODE: true
          SHOW_COMMIT: true
          SHOW_TITLE: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_PROJECTS: true
