name: Waka Readme

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_EDITORS: true
          SHOW_OS: true
